import Head from "next/head";
import FormComponent from "@/components/form";
import Todos from "./todos/todos";
import { useSWRConfig } from "swr";
import axios from "axios";
import { useState } from "react";

export default function Home() {
  const { mutate } = useSWRConfig();
  const [isShow, setIsShow] = useState(false);

  const handleSubmit = async (e, setValue, value) => {
    e.preventDefault();

    try {
      await axios.post("/todo", value);
      mutate("api/todo");
    } catch (error) {
      console.log(error);
    }

    setValue({ ...value, title: "", description: "" });
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className=''>
        <div className='container w-11/12 p-8 mx-auto mt-10 lg:w-[800px] bg-white rounded-xl'>
          {!isShow ? (
            <button
              onClick={() => setIsShow(true)}
              className='w-full p-2 bg-blue-500 rounded-md hover:bg-blue-600 custom-transition text-slate-50'
            >
              Add New Todo?!
            </button>
          ) : (
            <FormComponent
              mutate={mutate}
              handleSubmit={handleSubmit}
              cancel={() => setIsShow(false)}
            />
          )}
        </div>

        <div className='container w-11/12 p-8 mx-auto mt-10 lg:w-[800px] bg-white rounded-xl '>
          <Todos />
        </div>
      </main>
    </>
  );
}
