import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import TodoCard from "@/components/todo-card";
// import { Data } from "../../data/todos";
import useSwr, { useSWRConfig } from "swr";
import axios from "axios";
import FormComponent from "@/components/form";

const inter = Inter({ subsets: ["latin"] });

const fetcher = async () => {
  const { data } = await axios.get("api/todo");
  return data;
};

export default function Home() {
  const { mutate } = useSWRConfig();
  const { data, error } = useSwr("api/todo", fetcher);

  if (error) return <h3>Some error occurred! Please refresh the page</h3>;

  if (!data) return <h3>Loading...</h3>;

  const renderTodoList = () => {
    return data?.map((todo) => (
      <TodoCard mutate={mutate} todo={todo} key={todo._id} />
    ));
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className=''>
        <div className='container w-11/12 p-8 mx-auto mt-10 lg:w-[800px] bg-white rounded-xl'>
          <FormComponent mutate={mutate} />
        </div>

        <div className='container w-11/12 p-8 mx-auto mt-10 lg:w-[800px] bg-white rounded-xl '>
          {data.length <= 0 ? (
            <p>
              {" "}
              There is no todo list available yet, you can make a new one by
              clicking on the above button!{" "}
            </p>
          ) : (
            renderTodoList()
          )}
        </div>
      </main>
    </>
  );
}
